/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

import proyectofinal.ControllerLogin;

/**
 *
 * @author franz
 */
public class Login extends javax.swing.JDialog {

    private ControllerLogin ver = new ControllerLogin();

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void inicioSesion(){
        if (txtusuario.getText().isEmpty() || txtcontraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan datos");
        } else {
            switch (ver.verificarUsuarios(txtusuario.getText(), txtcontraseña.getText())) {
                case 1:
                    Registro ra = new Registro(null, true);
                    ra.setVisible(true);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "inicio exitoso", "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    //llevar a modulo de estudiante
                    break;
                case 3:
                    JOptionPane.showMessageDialog(null, "inicio exitoso", "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    //llevar a modulo de docentes
                     break;
                default:
                    JOptionPane.showMessageDialog(null, "Error contraseña o usuario incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }
    
    public void limpiar(){
        txtusuario.setText("");
        txtcontraseña.setText("");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtcontraseña = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesion ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 420, 24);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel3.setLayout(null);

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtusuario);
        txtusuario.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(85, 60, 250, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel2.setLayout(null);
        jPanel2.add(txtcontraseña);
        txtcontraseña.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(85, 120, 250, 50);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 200, 120, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 330);

        setSize(new java.awt.Dimension(430, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inicioSesion();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
