/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import proyectofinal.AREstudiantes;
import proyectofinal.ARdocentes;
import proyectofinal.ControllerLogin;


/**
 *
 * @author franz
 */
public class Registro extends javax.swing.JDialog {
    private ControllerLogin pro = new ControllerLogin();
    private ARdocentes doc = new ARdocentes();
    private AREstudiantes est = new AREstudiantes();
    

    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void RegistroDoc() {
        if (txtusuario.getText().isEmpty() || txtcorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan datos");
        } else {
            if (doc.verificarUsuario(txtusuario.getText())) {
                JOptionPane.showMessageDialog(null, "Usuario Existente", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (doc.registrarDos(txtusuario.getText(),txtcorreo.getText(), txtcontraseña.getText())) {
                    JOptionPane.showMessageDialog(null, "Registro exitoso", "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error Registro fallido", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    public void RegistroEst() {
        if (txtusuario.getText().isEmpty() || txtcorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan datos");
        } else {
            if (est.verificarUsuario(txtusuario.getText())) {
                JOptionPane.showMessageDialog(null, "Usuario Existente", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (est.registrarEst(txtusuario.getText(),txtcorreo.getText(), txtcontraseña.getText())) {
                    JOptionPane.showMessageDialog(null, "Registro exitoso", "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error Registro fallido", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    public void RegistroAd() {
        if (txtusuario.getText().isEmpty() || txtcorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan datos");
        } else {
            if (pro.verificarUsuario(txtusuario.getText())) {
                JOptionPane.showMessageDialog(null, "Usuario Existente", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (pro.registrarAd(txtusuario.getText(),txtcorreo.getText(), txtcontraseña.getText())) {
                    JOptionPane.showMessageDialog(null, "Registro exitoso", "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error Registro fallido", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    public void limpiar() {
        txtusuario.setText("");
        txtcorreo.setText("");
        txtcontraseña.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtcontraseña = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtcorreo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtcontraseña3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrate");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 400, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel3.setLayout(null);

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtusuario);
        txtusuario.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(75, 60, 250, 50);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Registar Adinistrador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 250, 160, 26);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel4.setLayout(null);
        jPanel4.add(txtcontraseña);
        txtcontraseña.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(80, 180, 250, 50);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        jPanel5.setLayout(null);
        jPanel5.add(txtcorreo);
        txtcorreo.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(75, 120, 250, 50);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel6.setLayout(null);
        jPanel6.add(txtcontraseña3);
        txtcontraseña3.setBounds(5, 17, 240, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(75, 120, 250, 50);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Registrar Estudiante");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 290, 150, 26);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setText("Registrar Docente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(150, 330, 160, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 390);

        setSize(new java.awt.Dimension(458, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegistroAd();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RegistroEst();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RegistroDoc();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtcontraseña3;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
