/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import modeloTabla.ModeloRegistroEstudiante;
import proyectofinal.AREstudiantes;
import proyectofinal.ControllerLogin;

/**
 *
 * @author franz
 */
public class RegistrarEstudiante extends javax.swing.JDialog {
    ControllerLogin log = new ControllerLogin();
    ModeloRegistroEstudiante mre = new ModeloRegistroEstudiante();
    AREstudiantes est = new AREstudiantes();
    /**
     * Creates new form RegistrarEstudiante
     */
    public RegistrarEstudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Limpiar();
    }
    private void Limpiar(){
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtIdentificacion.setText("");
        txtNombres.setText("");
        txtTelefono.setText("");
        if (est.listar()!=null){
            cargarTabla();
        }
    } 
    private void cargarTabla(){
        mre.setEstudiantes(est.listar());
        TablasEst.setModel(mre);
        TablasEst.updateUI();
    }
    private void RegistroEst() {
        if (txtApellidos.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtIdentificacion.getText().isEmpty()
                || txtNombres.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtcontrasena.getText().isEmpty() || txtcontrasenaval.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "LLene todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!log.verifiCorreo(txtCorreo.getText())) {
                if (!log.verificarCedula(txtIdentificacion.getText())) {
                    if (!log.verificarTelefono(txtTelefono.getText())) {
                        if (log.CoincidirCorreo(txtcontrasena.getText(), txtcontrasenaval.getText())) {
                            if (log.registrarCu(txtIdentificacion.getText(), txtCorreo.getText(),
                                    txtcontrasena.getText(), txtTelefono.getText()) ) {
                                JOptionPane.showMessageDialog(null, "Registro exitoso", "Mensaje de exito", JOptionPane.INFORMATION_MESSAGE);
                             Limpiar();
                            } else {
                                JOptionPane.showMessageDialog(null, "No se pudo registrar", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "La contraseña no coincide", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "telefono Existente", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cedula Existente", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario Existente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablasEst = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcontrasenaval = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtcontrasena = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Estudiantes");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Estudiantes");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 10, 160, 19);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        TablasEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablasEst.setMinimumSize(new java.awt.Dimension(20, 64));
        jScrollPane2.setViewportView(TablasEst);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 610, 120);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 280, 640, 160);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(120, 10, 110, 24);

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel3.add(txtTelefono);
        txtTelefono.setBounds(120, 170, 110, 30);

        jLabel3.setText("Tipo Identificacion");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 10, 100, 20);

        jLabel4.setText("Confirmar Contraseña");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 130, 120, 20);

        jLabel5.setText("Telefono");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 170, 70, 20);

        jLabel6.setText("Identificacion");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 50, 70, 20);
        jPanel3.add(txtcontrasenaval);
        txtcontrasenaval.setBounds(490, 130, 110, 30);
        jPanel3.add(txtNombres);
        txtNombres.setBounds(120, 90, 110, 30);

        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdentificacion);
        txtIdentificacion.setBounds(120, 50, 110, 30);

        jLabel7.setText("Nombres");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 90, 70, 20);

        jLabel8.setText("Grado o curso");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(350, 10, 80, 20);

        jLabel9.setText("Contraseña");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(350, 90, 70, 20);

        jLabel10.setText("Correo");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(350, 50, 70, 20);
        jPanel3.add(txtCorreo);
        txtCorreo.setBounds(490, 50, 110, 30);
        jPanel3.add(txtcontrasena);
        txtcontrasena.setBounds(490, 90, 110, 30);

        jLabel11.setText("Apellidos");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 130, 70, 20);
        jPanel3.add(txtApellidos);
        txtApellidos.setBounds(120, 130, 110, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(490, 10, 100, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 40, 640, 210);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 250, 80, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 450);

        setSize(new java.awt.Dimension(674, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegistroEst();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarEstudiante dialog = new RegistrarEstudiante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablasEst;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtcontrasena;
    private javax.swing.JTextField txtcontrasenaval;
    // End of variables declaration//GEN-END:variables
}
