/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controlador;
import javax.swing.table.DefaultTableModel;
public class Sistemalumnos extends javax.swing.JFrame {

    public Sistemalumnos() {
        initComponents();
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
        "UNIDAD 1", "UNIDAD 2", "UNIDAD 3", "PROMEDIO TOTAL"
    }
));
         Controlador controlador = new Controlador();
         controlador.cargarDatos(this);
    }
    public void setNombreEstudiante(String nombre) {
        jLabel10.setText(nombre);
    }

    // Setter para el correo del estudiante
    public void setCorreoEstudiante(String correo) {
        jLabel11.setText(correo);
    }
    public void setPromedioFinal(double promedio) {
    jLabel12.setText(String.format("%.2f", promedio));


    }
    public void setTableModel(DefaultTableModel model) {
        jTable2.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE CALIFICACIONES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 270, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Estudiante:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 80, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 37, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Correo Electrónico:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 80, 140, 20);

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 40, 450, 30);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 80, 150, 30);

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 80, 200, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 620, 120);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Resumen:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 10, 130, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("MATERIAS");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(220, 40, 90, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("PROMEDIO ");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(370, 40, 153, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(220, 10, 100, 30);

        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(360, 10, 110, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 280, 620, 80);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UNIDAD 1", "UNIDAD 2", "UNIDAD 3", "PROMEDIO TOTAL"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 150, 620, 110);

        setSize(new java.awt.Dimension(677, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistemalumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistemalumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistemalumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistemalumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistemalumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
